version: "3.9"
services:
  db:
    container_name: music-api
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  app:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db